"""Project-wide constants."""

GEMINI_EMBEDDING_MODEL = "gemini-embedding-2-preview"
GEMINI_VISION_MODEL = "gemini-3.1-flash-lite-preview"
DEFAULT_EMBEDDING_DIMS = 3072
MATRYOSHKA_DIMS = [128, 768, 1536, 3072]
MAX_VIDEO_SECONDS_WITH_AUDIO = 80
MAX_VIDEO_SECONDS_NO_AUDIO = 120
MAX_AUDIO_SECONDS = 80
MAX_IMAGES_PER_REQUEST = 6
MAX_PDF_PAGES = 6
MAX_TEXT_TOKENS = 8192
PINECONE_NS_CREATIVES = "creatives"
PINECONE_NS_BRAND = "brand_assets"
